apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: bookify
  labels:
    role: api
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: api
        image: public.ecr.aws/q9a3t3s6/server:latest
        imagePullPolicy: Always
        env:
          - name: MONGODB_STRING
            value: mongodb://mongodb-svc:27017/admin?directConnection=true
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
        ports:
        - containerPort: 5000